import Nav from './Nav/Nav'
import NavMobile from './navMobile/NavMobile'
import '@fortawesome/fontawesome-svg-core/styles.css'
import 'bootstrap/dist/css/bootstrap.css';
import Footer from './Footer/Footer'
import { CartProvider } from './CartContext';
import Alerts from './Alert/Alert';
import './globals.css'


export const metadata = {
  title: 'E-Commerce',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Nav />
          <NavMobile />
          <Alerts />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}
